version: 2

jobs:
  build:
    docker:
      - image: nixos/nix
    # Not required, because DNA is build in .../hApp-store sub-directory
    working_directory: ~/hApp-store
    steps:
      - checkout
      - run: |
          nix-env -f pkgs.nix -iA git bash gnumake
      - run: |
          nix-shell \
            --option substituters 'https://cache.holo.host https://cache.nixos.org' \
            --option trusted-public-keys \
              'cache.holo.host-1:lNXIXtJgS9Iuw4Cu6X0HINLu9sTfcjEntnrgwMQIMcE=
               cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=' \
            --run 'make test'
